pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import index, products
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import products, basket_add, basket_remove, about, news, review_send, review, term, contacts, promo, confidentiality, vacancies, test, test2, news_detail, test3, test4, banner_settings_view, get_rotation_interval, update_rotation_interval

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('about', about, name='about'),
    path('news', news, name='news'),
    path('term', term, name='term'),
    path('contacts', contacts, name='contacts'),
    path('promo', promo, name='promo'),
    path('confidentiality', confidentiality, name='confidentiality'),
    path('vacancies', vacancies, name='vacancies'),
    path('test', test, name='test'),
    path('test2', test2, name='test2'),
    path('test3', test3, name='test3'),
    path('test4', test4, name='test4'),
    path('news_details/<title>', news_detail, name='news_details'),
    path('banner-settings/', banner_settings_view, name='banner_settings'),
    path('get-rotation-interval/', get_rotation_interval, name='get_rotation_interval'),
    path('update_rotation_interval/', update_rotation_interval, name='update_rotation_interval'),

    path('review_send', review_send, name='review_send'),
    path('review', review, name='review'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

products/models.py
from django.db import models
from users.models import User

# Create your models here.


class Banner(models.Model):
    image = models.ImageField(upload_to='banners/')
    link = models.URLField()


class BannerSettings(models.Model):
    rotation_interval = models.PositiveIntegerField(default=5000)
    zalups = models.IntegerField(max_length=8)


class NewsArticle(models.Model):
    title = models.CharField(max_length=255, blank=True)
    description = models.TextField()
    img = models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Empty_set_symbol.svg/640px-Empty_set_symbol.svg.png')
    url = models.URLField()
    timestamp = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    username = models.CharField(max_length=120, blank=True)
    grade = models.CharField(max_length=5, blank=True)
    text_review = models.CharField(max_length=2000)
    timestamp = models.DateTimeField(auto_now_add=True)


class FAQ(models.Model):
    term = models.CharField(max_length=100)
    definition = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


class ProductCategory(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    created_timestamp = models.DateField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f"Корзина {self.user.email}, продукт - {self.product.name}"

    def sum(self):
        return self.product.price * self.quantity

products/forms.py
# forms.py
from django import forms
from .models import BannerSettings


class ProductSearchForm(forms.Form):
    search_query = forms.CharField(label='Поиск', max_length=100)


class BannerSettingsForm(forms.ModelForm):
    class Meta:
        model = BannerSettings
        fields = ['rotation_interval']

products/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from products.models import Product, ProductCategory, Basket, NewsArticle, Review, FAQ, Banner
from django.contrib.auth.decorators import login_required
import requests
import random
from .forms import ProductSearchForm
from django.http import JsonResponse
from users.models import User
from .models import BannerSettings
from .forms import BannerSettingsForm

# Create your views here.

import logging

logger = logging.getLogger(__name__)


def get_rotation_interval(request):
    banner_settings = BannerSettings.objects.first()
    rotation_interval = banner_settings.rotation_interval if banner_settings else 5000  # Значение по умолчанию, если записей нет
    return JsonResponse({'rotation_interval': rotation_interval})

def banner_settings_view(request):
    banner_settings = BannerSettings.objects.first()  # Получаем первый объект BannerSettings или создаем новый при необходимости

    if request.method == 'POST':
        form = BannerSettingsForm(request.POST, instance=banner_settings)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        form = BannerSettingsForm(instance=banner_settings)

    return render(request, 'products/index.html', {'form': form})



def my_view(request):
    logger.debug('Debug message')  # Пример логирования с уровнем DEBUG
    logger.info('Info message')    # Пример логирования с уровнем INFO
    logger.warning('Warning message')  # Пример логирования с уровнем WARNING
    logger.error('Error message')      # Пример логирования с уровнем ERROR
    logger.critical('Critical message')  # Пример логирования с уровнем CRITICAL


def index(request):
    context = {
        'title': 'main',
        'last_news': NewsArticle.objects.last(),
        'banners': Banner.objects.all(),
        'interval': BannerSettings.objects.first().rotation_interval,
    }
    return render(request, 'products/index.html', context)


def update_rotation_interval(request):
    if request.method == 'POST':
        rotation_interval = request.POST.get('rotation_interval')  # Получаем значение из POST запроса
        # print(rotation_interval)
        banner_settings = BannerSettings.objects.first()  # Получаем первый объект модели

        if banner_settings:
            banner_settings.rotation_interval = rotation_interval  # Обновляем значение
            banner_settings.save()  # Сохраняем изменения
    context = {
        'title': 'main',
        'last_news': NewsArticle.objects.last(),
        'banners': Banner.objects.all(),
        'interval': BannerSettings.objects.first().rotation_interval,
    }
    return render(request, 'products/index.html', context)


def promo(request):
    context = {
        'title': 'promo',
    }
    return render(request, 'products/promo.html', context)


def vacancies(request):
    context = {
        'title': 'promo',
    }
    return render(request, 'products/vacancies.html', context)


def category(request):
    context = {
        'title': 'promo',
    }
    return render(request, 'products/vacancies.html', context)


def confidentiality(request):
    context = {
        'title': 'confidentiality',
    }
    return render(request, 'products/confidentiality.html', context)


def contacts(request):
    context = {
        'title': 'contacts',
    }
    return render(request, 'products/contacts.html', context)


def term(request):
    context = {
        'title': 'main',
        'terms': FAQ.objects.all(),
    }
    return render(request, 'products/faq.html', context)


def review(request):
    context = {
        'reviews': Review.objects.all()
    }
    return render(request, 'products/review.html', context)


def products(request):
    products_ = Product.objects.all()
    search_form = ProductSearchForm(request.GET)

    if search_form.is_valid():
        search_query = search_form.cleaned_data['search_query']
        products_ = products_.filter(name__icontains=search_query)

    context = {
        'title': 'products',
        'products': products_,
        'categories': ProductCategory.objects.all(),
        'search_form': search_form,
    }
    return render(request, 'products/products.html', context)


def about(request):
    context = {
        'title': 'about',
    }
    return render(request, 'products/about.html', context)


def test(request):
    context = {
        'title': 'test',
    }
    return render(request, 'products/test.html', context)


def test2(request):
    context = {
        'title': 'test2',
    }
    return render(request, 'products/test2.html', context)

def test3(request):
    context = {
        'title': 'test2',
    }
    return render(request, 'products/test3.html', context)

def test4(request):
    context = {
        'title': 'test2',
    }
    return render(request, 'products/test4.html', context)

def news_detail(request, title):
    context = {
        'title': 'news_detail',
        'article': NewsArticle.objects.filter(title=title)
    }
    return render(request, 'products/full_article.html', context)


def news(request):
    url = 'https://newsapi.org/v2/everything?q=pizza&apiKey=20d95eef27454a9e990d505cb55f92cf'
    # pizza_news = requests.get(url).json()
    # i = random.randint(1, 100)
    # a = pizza_news['articles']
    # desc = []
    # title = []
    # img = []
    # news_url = []
    #
    # f = a[i]
    # title = f['title']
    # desc = f['description']
    # img = f['urlToImage']
    # news_url = f['url']
    #
    # existing_article = NewsArticle.objects.filter(title=title).first()
    # if existing_article:
    #     existing_article.description = desc
    #     existing_article.img = img
    #     existing_article.url = news_url
    #     existing_article.save()
    # else:
    #     new_article = NewsArticle(
    #         title=title,
    #         description=desc,
    #         img=img,
    #         url=news_url
    #     )
    #     new_article.save()

    context = {'news': NewsArticle.objects.all()}
    return render(request, 'products/news.html', context)

# @csrf_exempt
# def news_view(request):
#     # Вызываем представление get_news для получения новостей
#     news_data = get_news(request)
#
#     # Если есть статьи новостей, передаем их в шаблон
#     if 'articles' in news_data:
#         articles = news_data['articles']
#         return render(request, 'products/news.html', {'articles': articles})
#
#     # Если произошла ошибка, передаем ошибку в шаблон
#     elif 'error' in news_data:
#         error_message = news_data['error']
#         return render(request, 'products/news.html', {'error_message': error_message})
#
#     return render(request, 'products/news.html', {'error_message': 'Что-то пошло не так'})
#
#
#
# def get_news(request):
#     api_key = '20d95eef27454a9e990d505cb55f92cf'
#     api_url = f'https://newsapi.org/v2/everything?q=pizza&apiKey={api_key}'
#
#     try:
#         response = requests.get(api_url)
#         data = response.json()
#
#         if data.get('articles'):
#             articles = data['articles']
#             return JsonResponse({'articles': articles})
#
#     except Exception as e:
#         return JsonResponse({'error': str(e)})
#
#     return JsonResponse({'error': 'Не удалось получить новости'})
#
# @csrf_exempt
# def refresh_news(request):
#     # Вызываем представление get_news для получения новостей
#     news_data = get_news(request)
#
#     # Если есть статьи новостей, добавляем первую в базу данных
#     if 'articles' in news_data:
#         articles = news_data['articles']
#         if articles:
#             article_data = articles[0]
#             NewsArticle.objects.create(
#                 title=article_data['title'],
#                 description=article_data['description'],
#                 url=article_data['url']
#             )
#             return JsonResponse({'status': 'success'})
#
#     return JsonResponse({'error': 'Не удалось обновить новости'})

@login_required
def review_send(request):
    if request.method == 'POST':
        rating = request.POST['rating']
        review_text = request.POST['review-text']
        username = request.user.username

        review = Review(username=username, grade=rating, text_review=review_text)
        review.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])



@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/faq.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>

        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 0;
        }

        h1 {
            text-align: center;
        }

        .glossary {
            list-style-type: none;
            padding: 0;
        }

        .term {
            margin: 10px 0;
        }

        /* Стили для скрытых определений */
        .definition {
            display: none;
        }

        /* Стили для активных терминов */
        a.toggle {
            text-decoration: none;
            color: blue;
            cursor: pointer;
        }

        a.toggle:hover {
            text-decoration: underline;
        }

        h1 {
            font-size: 24px;
            margin: 20px 0;
        }

        /* Стили для контейнера FAQ */
        .glossary {
            list-style: none;
            padding: 0;
        }

        /* Стили для каждого вопроса и ответа */
        .faq {
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 10px;
        }

        /* Стили для заголовка вопроса */
        details summary {
            cursor: pointer;
            font-weight: bold;
            padding: 5px;
            background-color: orange;
            border: 1px solid #26c7d7;
            border-radius: 5px;
        }

        /* Стили для текста ответа */
        details p {
            margin: 10px 0;
        }

        /* Стили для даты создания */
        .date {
            font-style: italic;
        }
    </style>
{% endblock %}

{% block content %}
    <body>
    <h1>Часто задаваемые вопросы</h1>
    <ul class="glossary">
        {% for term in terms %}
            <div class="faq">
                <details>
                    <summary>
                        {{ term.term }}
                    </summary>
                    <p class="date">Дата создания: {{ term.timestamp|date:"d.m.Y" }}</p>
                    <p>{{ term.definition }}</p>
                </details>
            </div>
        {% endfor %}
    </ul>
</body>
{% endblock %}

products/templates/products/news.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    <style>

        p::first-line {
            font-size: 120%;
            font-style: italic;
            color: #007bff;
        }

        /* Стили для краткой информации и кнопки "Читать далее" */
        .article-summary {
            max-height: 3em; /* Ограничение высоты для краткой информации */
            overflow: hidden;
            text-overflow: ellipsis; /* Многоточие для обрезанного текста */
        }

        .read-more {
            margin-top: 10px;
        }

        /* Стили для многоколоночного макета */
        .article {
            display: flex;
            flex-wrap: wrap;
        }

        .article .media {
            flex: 1; /* Равное распределение по колонкам */
        }
    </style>
{% endblock %}

{% block content %}
    <body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Новости
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="rows">
                <div class="column is-offset-16 is-10">
                    {% for obj in news %}
                        <div class="box">
                            <article class="media">
                                <div class="media-content">
                                    <div class="content">
                                        <p>
                                            <span class="title">{{ obj.title }}</span>
                                            <br>
                                            <img src="{{ obj.img }}" alt="">
                                            <span class="subtitle">{{ obj.description }}</span>
                                        </p>
                                    </div>
                                </div>
                            </article>
                            Дата и время: {{ obj.timestamp|date:"F j, Y H:i:s" }}
                            <a href="{% url 'products:news_details' obj.title %}">Читать далее</a>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <title>Новости</title>#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />#}
{#    <style>#}
{##}
{#        p::first-line {#}
{#            font-size: 120%;#}
{#            font-style: italic;#}
{#            color: #007bff;#}
{#        }#}
{##}
{#        /* Стили для краткой информации и кнопки "Читать далее" */#}
{#        .article-summary {#}
{#            max-height: 3em; /* Ограничение высоты для краткой информации */#}
{#            overflow: hidden;#}
{#            text-overflow: ellipsis; /* Многоточие для обрезанного текста */#}
{#        }#}
{##}
{#        .read-more {#}
{#            margin-top: 10px;#}
{#        }#}
{##}
{#        /* Стили для многоколоночного макета */#}
{#        .article {#}
{#            display: flex;#}
{#            flex-wrap: wrap;#}
{#        }#}
{##}
{#        .article .media {#}
{#            flex: 1; /* Равное распределение по колонкам */#}
{#        }#}
{#    </style>#}
{#</head>#}
{#<body>#}
{#    <section class="hero is-primary">#}
{#        <div class="hero-body">#}
{#            <div class="container">#}
{#                <h1 class="title">#}
{#                    Новости#}
{#                </h1>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{#    <section class="section">#}
{#        <div class="container">#}
{#            <div class="rows">#}
{#                <div class="column is-offset-16 is-10">#}
{#                    {% for obj in news %}#}
{#                        <div class="box">#}
{#                            <article class="media">#}
{#                                <div class="media-content">#}
{#                                    <div class="content">#}
{#                                        <p>#}
{#                                            <span class="title">{{ obj.title }}</span>#}
{#                                            <br>#}
{#                                            <img src="{{ obj.img }}" alt="">#}
{#                                            <span class="subtitle">{{ obj.description }}</span>#}
{#                                        </p>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </article>#}
{#                            Дата и время: {{ obj.timestamp|date:"F j, Y H:i:s" }}#}
{#                            <a href="{% url 'products:news_details' obj.title %}">Читать далее</a>#}
{#                        </div>#}
{#                    {% endfor %}#}
{##}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{#    <footer class="footer">#}
{#    </footer>#}
{#</body>#}
{#</html>#}

products/templates/products/order.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Заказ доставки пиццы</title>
</head>
<body>
    <h1>Оформление заказа доставки пиццы</h1>
    <form action="обработчик.php" method="POST">
        <label for="name">Имя:</label>
        <input type="text" id="name" name="name" required>
        <br><br>

        <label for="address">Адрес доставки:</label>
        <input type="text" id="address" name="address" required>
        <br><br>

        <label for="phone">Номер телефона:</label>
        <input type="tel" id="phone" name="phone" required>
        <br><br>

        <input type="submit" value="Заказать пиццу">
    </form>
</body>
</html>

products/templates/products/review.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <meta charset="UTF-8">
    <title>Отзывы</title>
    <style>
        {#/* Стили для страницы */#}
        {#body {#}
        {#    font-family: Arial, sans-serif;#}
        {#    margin: 20px;#}
        {#}#}
        {#.review {#}
        {#    border: 1px solid #ccc;#}
        {#    padding: 10px;#}
        {#    margin-bottom: 10px;#}
        {#}#}
        {#.review p {#}
        {#    margin: 0;#}
        {#}#}
        {##add-review {#}
        {#    margin-top: 20px;#}
        {#}#}
        /* Стили для страницы */
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        /* Стили для отзывов */
        .review {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 10px;
        }

        .review p {
            margin: 0;
        }

        /* Стили для заголовка "Добавить отзыв" */
        #add-review h2 {
            font-size: 24px;
            font-weight: bold;
            text-transform: uppercase;
        }

        /* Стили для формы */
        form {
            font-family: Arial, sans-serif;
            margin-top: 20px;
        }

        /* Стили для оценки (select) */
        #rating {
            font-size: 16px;
            padding: 5px;
        }

        /* Стили для текстового поля отзыва (textarea) */
        #review-text {
            font-family: Arial, sans-serif;
            font-size: 16px;
            padding: 10px;
            width: 100%;
        }

        /* Стили для кнопки "Отправить" */
        input[type="submit"] {
            font-family: Arial, sans-serif;
            font-size: 16px;
            padding: 10px 20px;
            background-color: #3498db;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        /* Стили для списка отзывов */
        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin: 0 0 20px;
            font-family: Arial, sans-serif;
            font-size: 16px;
            border: 1px solid #ccc;
            padding: 10px;
        }

        /* Стили для данных отзывов */
        li strong {
            font-weight: bold;
        }

        /* Стили для сообщения "Пока нет отзывов" */
        p {
            font-family: Arial, sans-serif;
            font-size: 16px;
        }

    </style>
{% endblock %}

{% block content %}
    <body>
{#    <h1>Отзывы</h1>#}
{##}
{#    <!-- Список отзывов -->#}
{#    <div class="review">#}
{#        <p><strong>Имя:</strong> John Doe</p>#}
{#        <p><strong>Оценка:</strong> 5 звезд</p>#}
{#        <p><strong>Текст:</strong> Отличное место, вкусная пицца!</p>#}
{#        <p><strong>Дата:</strong> 2023-09-14</p>#}
{#    </div>#}

    <!-- Добавление отзыва (требуется регистрация/вход) -->
    <div id="add-review">
        <h2>Добавить отзыв</h2>
        <form action="{% url 'products:review_send' %}" method="post">
            {% csrf_token %}
            <label for="rating">Оценка:</label>
            <select id="rating" name="rating" required>
                <option value="★★★★★">★★★★★</option>
                <option value="★★★★">★★★★</option>
                <option value="★★★">★★★</option>
                <option value="★★">★★</option>
                <option value="★">★</option>
            </select><br>

            <label for="review-text">Текст отзыва:</label><br>
            <textarea id="review-text" name="review-text" rows="4" required></textarea><br>

            <input type="submit" value="Отправить" href="{% url 'products:review_send' %}">
        </form>
    </div>

    <h1>Отзывы</h1>

    {% if reviews %}
        <ul>
            {% for review in reviews %}
                <li>
                    <strong>Имя:</strong> {{ review.username }}<br>
                    <strong>Оценка:</strong> {{ review.grade }}<br>
                    <strong>Текст:</strong> {{ review.text_review }}<br>
                    <strong>Дата:</strong> {{ review.timestamp }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Пока нет отзывов.</p>
    {% endif %}
</body>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Отзывы</title>#}
{#    <style>#}
        {#/* Стили для страницы */#}
        {#body {#}
        {#    font-family: Arial, sans-serif;#}
        {#    margin: 20px;#}
        {#}#}
        {#.review {#}
        {#    border: 1px solid #ccc;#}
        {#    padding: 10px;#}
        {#    margin-bottom: 10px;#}
        {#}#}
        {#.review p {#}
        {#    margin: 0;#}
        {#}#}
        {##add-review {#}
        {#    margin-top: 20px;#}
        {#}#}
{#        /* Стили для страницы */#}
{#        body {#}
{#            font-family: Arial, sans-serif;#}
{#            margin: 20px;#}
{#        }#}
{##}
{#        /* Стили для отзывов */#}
{#        .review {#}
{#            border: 1px solid #ccc;#}
{#            padding: 10px;#}
{#            margin-bottom: 10px;#}
{#        }#}
{##}
{#        .review p {#}
{#            margin: 0;#}
{#        }#}
{##}
{#        /* Стили для заголовка "Добавить отзыв" */#}
{#        #add-review h2 {#}
{#            font-size: 24px;#}
{#            font-weight: bold;#}
{#            text-transform: uppercase;#}
{#        }#}
{##}
{#        /* Стили для формы */#}
{#        form {#}
{#            font-family: Arial, sans-serif;#}
{#            margin-top: 20px;#}
{#        }#}
{##}
{#        /* Стили для оценки (select) */#}
{#        #rating {#}
{#            font-size: 16px;#}
{#            padding: 5px;#}
{#        }#}
{##}
{#        /* Стили для текстового поля отзыва (textarea) */#}
{#        #review-text {#}
{#            font-family: Arial, sans-serif;#}
{#            font-size: 16px;#}
{#            padding: 10px;#}
{#            width: 100%;#}
{#        }#}
{##}
{#        /* Стили для кнопки "Отправить" */#}
{#        input[type="submit"] {#}
{#            font-family: Arial, sans-serif;#}
{#            font-size: 16px;#}
{#            padding: 10px 20px;#}
{#            background-color: #3498db;#}
{#            color: #fff;#}
{#            border: none;#}
{#            cursor: pointer;#}
{#        }#}
{##}
{#        /* Стили для списка отзывов */#}
{#        ul {#}
{#            list-style: none;#}
{#            padding: 0;#}
{#        }#}
{##}
{#        li {#}
{#            margin: 0 0 20px;#}
{#            font-family: Arial, sans-serif;#}
{#            font-size: 16px;#}
{#            border: 1px solid #ccc;#}
{#            padding: 10px;#}
{#        }#}
{##}
{#        /* Стили для данных отзывов */#}
{#        li strong {#}
{#            font-weight: bold;#}
{#        }#}
{##}
{#        /* Стили для сообщения "Пока нет отзывов" */#}
{#        p {#}
{#            font-family: Arial, sans-serif;#}
{#            font-size: 16px;#}
{#        }#}
{##}
{#    </style>#}
{#</head>#}
{#<body>#}
{#    <h1>Отзывы</h1>#}
{##}
{#    <!-- Список отзывов -->#}
{#    <div class="review">#}
{#        <p><strong>Имя:</strong> John Doe</p>#}
{#        <p><strong>Оценка:</strong> 5 звезд</p>#}
{#        <p><strong>Текст:</strong> Отличное место, вкусная пицца!</p>#}
{#        <p><strong>Дата:</strong> 2023-09-14</p>#}
{#    </div>#}
{##}
{#    <!-- Добавление отзыва (требуется регистрация/вход) -->#}
{#    <div id="add-review">#}
{#        <h2>Добавить отзыв</h2>#}
{#        <form action="{% url 'products:review_send' %}" method="post">#}
{#            {% csrf_token %}#}
{#            <label for="rating">Оценка:</label>#}
{#            <select id="rating" name="rating" required>#}
{#                <option value="★★★★★">★★★★★</option>#}
{#                <option value="★★★★">★★★★</option>#}
{#                <option value="★★★">★★★</option>#}
{#                <option value="★★">★★</option>#}
{#                <option value="★">★</option>#}
{#            </select><br>#}
{##}
{#            <label for="review-text">Текст отзыва:</label><br>#}
{#            <textarea id="review-text" name="review-text" rows="4" required></textarea><br>#}
{##}
{#            <input type="submit" value="Отправить" href="{% url 'products:review_send' %}">#}
{#        </form>#}
{#    </div>#}
{##}
{#    <h1>Отзывы</h1>#}
{##}
{#    {% if reviews %}#}
{#        <ul>#}
{#            {% for review in reviews %}#}
{#                <li>#}
{#                    <strong>Имя:</strong> {{ review.username }}<br>#}
{#                    <strong>Оценка:</strong> {{ review.grade }}<br>#}
{#                    <strong>Текст:</strong> {{ review.text_review }}<br>#}
{#                    <strong>Дата:</strong> {{ review.timestamp }}#}
{#                </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% else %}#}
{#        <p>Пока нет отзывов.</p>#}
{#    {% endif %}#}
{#</body>#}
{#</html>#}